# Generated by Django 5.1.2 on 2024-11-18 17:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Employee Name')),
                ('phone', models.CharField(max_length=20, verbose_name='phone number')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Activate')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Specialization Name')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Is Booked')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='partner_portal.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255, null=True, verbose_name='business Name')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Phone Number')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('team_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Team Size')),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=17, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=17, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_certificate_image', models.CharField(max_length=255, null=True)),
                ('selected_services', models.ManyToManyField(blank=True, to='core.servicetype', verbose_name='Selected Services')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='partner_portal.partnerdetail')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='partner_portal.partnerdetail'),
        ),
        migrations.CreateModel(
            name='PartnerImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_slides', to='partner_portal.partnerdetail')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partner_portal.specialization', verbose_name='Specialization'),
        ),
    ]
