# Generated by Django 5.1.2 on 2024-11-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=125, unique=True),
        ),
    ]
