# Generated by Django 5.1.2 on 2024-11-24 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeavailability',
            name='is_unavailable',
            field=models.BooleanField(default=False, verbose_name='Is Unavailable'),
        ),
        migrations.AddField(
            model_name='partneravailability',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Specific Date'),
        ),
        migrations.AddField(
            model_name='partneravailability',
            name='is_weekly',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='partneravailability',
            name='weekday',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='partneravailability',
            unique_together={('partner', 'weekday', 'date', 'start_time', 'end_time')},
        ),
        migrations.CreateModel(
            name='PartnerHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Holiday Date')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='partner_portal.partnerdetail')),
            ],
        ),
    ]
