# Generated by Django 5.1.2 on 2024-11-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_portal', '0002_employeeavailability_is_unavailable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partneravailability',
            old_name='date',
            new_name='specific_date',
        ),
        migrations.AlterUniqueTogether(
            name='partneravailability',
            unique_together={('partner', 'weekday', 'specific_date', 'start_time', 'end_time')},
        ),
    ]
