# Generated by Django 5.1.2 on 2024-11-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_portal', '0002_alter_servicetype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerdetail',
            name='company_name',
        ),
        migrations.AddField(
            model_name='partnerdetail',
            name='business_name',
            field=models.CharField(max_length=255, null=True, verbose_name='business Name'),
        ),
    ]
