# Generated by Django 5.1.2 on 2024-11-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_portal', '0003_remove_partnerdetail_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerdetail',
            name='selected_services',
            field=models.ManyToManyField(blank=True, to='partner_portal.servicetype', verbose_name='Selected Services'),
        ),
        migrations.AddField(
            model_name='partnerdetail',
            name='team_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Team Size'),
        ),
    ]
