# Generated by Django 5.1.2 on 2024-11-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_portal', '0003_rename_date_partneravailability_specific_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeavailability',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='employeeavailability',
            name='start_time',
            field=models.TimeField(db_index=True, verbose_name='Start Time'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeavailability',
            unique_together={('employee', 'date', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='employeeavailability',
            index=models.Index(fields=['employee', 'date', 'start_time'], name='partner_por_employe_6ff605_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeavailability',
            index=models.Index(fields=['date', 'start_time'], name='partner_por_date_182d31_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeavailability',
            index=models.Index(fields=['is_booked'], name='partner_por_is_book_b6532f_idx'),
        ),
    ]
