# Generated by Django 5.1.2 on 2024-11-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_portal', '0004_alter_employeeavailability_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='phone number'),
        ),
    ]
