# Generated by Django 5.1.2 on 2024-11-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_portal', '0004_partnerdetail_selected_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerdetail',
            name='license_certificate_image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
