# Generated by Django 5.1.2 on 2024-11-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_portal', '0005_alter_employee_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('otp', models.CharField(max_length=6, verbose_name='OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
