# Generated by Django 5.1.2 on 2024-11-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_portal', '0005_alter_partnerdetail_license_certificate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerdetail',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=28, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='partnerdetail',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=28, verbose_name='Longitude'),
        ),
    ]
