# Generated by Django 5.1.2 on 2024-12-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_portal', '0006_employeeotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeavailability',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Is Locked'),
        ),
        migrations.AddField(
            model_name='employeeavailability',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Locked Until'),
        ),
    ]
