# Generated by Django 5.1.2 on 2024-12-25 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_portal', '0007_employeeavailability_is_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=20)),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='partner_portal.partnerdetail')),
            ],
        ),
    ]
