# Generated by Django 5.1.2 on 2024-12-26 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_portal', '0009_subscriptionplan_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerdetail',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_subscription', to='partner_portal.subscription'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_detail', to='partner_portal.partnerdetail'),
        ),
    ]
