# Generated by Django 5.1.2 on 2024-11-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_portal', '0010_alter_partnerdetail_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerdetail',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=17, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='partnerdetail',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=17, verbose_name='Longitude'),
        ),
    ]
