# Generated by Django 5.1.2 on 2025-01-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_portal', '0010_partnerdetail_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerdetail',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is Approved'),
        ),
    ]
