# Generated by Django 5.1.2 on 2025-01-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_ticket'),
        ('partner_portal', '0011_partnerdetail_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='service_types',
            field=models.ManyToManyField(blank=True, related_name='employees', to='core.servicetype', verbose_name='Service Types'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone Number'),
        ),
    ]
