# Generated by Django 5.1.2 on 2024-11-18 07:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('partner_portal', '0011_alter_partnerdetail_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Specialization Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='partner',
        ),
        migrations.AlterField(
            model_name='partnerdetail',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='partnerdetail',
            name='selected_services',
            field=models.ManyToManyField(blank=True, to='core.servicetype', verbose_name='Selected Services'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Employee Name')),
                ('phone', models.CharField(max_length=20, verbose_name='phone number')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Activate')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='partner_portal.partnerdetail')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partner_portal.specialization', verbose_name='Specialization')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='start name')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Is Booked')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='partner_portal.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='partner_portal.partnerdetail')),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
