# Generated by Django 5.1.2 on 2024-12-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('partner', 'Business Partner'), ('admin', 'Admin')], default='customer', max_length=50),
        ),
    ]
