services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - media_data:/app/media
      - static_data:/app/static
    ports:
      - "8000:8000"
      - /root/hipsta/.env
    command: >
      bash -c "/app/venv/bin/python manage.py migrate &&
               /app/venv/bin/python manage.py collectstatic --noinput &&
               /app/venv/bin/daphne -b 0.0.0.0 -p 8000 hipsta_server.asgi:application"

    depends_on:
      - db
      - redis
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/auth/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - hipsta-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - hipsta-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - hipsta-network

  celery:
      build:
        context: .
        dockerfile: Dockerfile.prod
      command: celery -A hipsta_server worker --pool=solo -l info
      depends_on:
        - redis
        - db
      environment:
        SECRET_KEY: ${SECRET_KEY}
        CELERY_BROKER_URL: ${CELERY_BROKER_URL}
        CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      restart: always
      networks:
        - hipsta-network
      env_file:
        - /root/hipsta/.env  # Point to the .env file on the server

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A hipsta_server beat --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      SECRET_KEY: ${SECRET_KEY}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    restart: always
    networks:
      - hipsta-network
    env_file:
      - /root/hipsta/.env  # Point to the .env file on the server

volumes:
  db_data:
  media_data:
  static_data:
  redis_data:

networks:
  hipsta-network:
    driver: bridge
