# Generated by Django 5.1.2 on 2024-11-18 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('partner_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='partner_portal.partnerdetail'),
        ),
        migrations.AddField(
            model_name='service',
            name='business_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.servicetype'),
        ),
    ]
