# Generated by Django 5.1.2 on 2024-12-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ticket_priority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
