# Generated by Django 5.1.2 on 2025-01-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.AddField(
            model_name='banner',
            name='image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
