# Generated by Django 5.1.2 on 2025-01-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_banner_image_banner_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='image',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
