# Generated by Django 5.1.2 on 2025-01-14 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_appointment_payment_method'),
        ('core', '0006_delete_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.service', verbose_name='Service'),
        ),
    ]
