name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

      - name: Deploy with Docker
        run: |
          set -x  # Enable debug mode to print each command being executed
          
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DO_HOST }} "
            set -x  # Enable debug mode inside the SSH session too
            
            if [ ! -d '/root/hipsta' ]; then
              echo 'Cloning repository...';
              git clone https://github.com/jishnu2040/hipsta.git /root/hipsta;
            else
              echo 'Pulling latest changes...';
              cd /root/hipsta && git pull origin main;
            fi &&
          
            # Ensure the .env.production file is correctly set up with all necessary variables
            echo \"SECRET_KEY=${{ secrets.SECRET_KEY }}\" > /root/hipsta/.env.production &&
            echo \"DB_NAME=${{ secrets.DB_NAME }}\" >> /root/hipsta/.env.production &&
            echo \"DB_USER=${{ secrets.DB_USER }}\" >> /root/hipsta/.env.production &&
            echo \"DB_PASSWORD=${{ secrets.DB_PASSWORD }}\" >> /root/hipsta/.env.production &&
            echo \"DB_HOST=${{ secrets.DB_HOST }}\" >> /root/hipsta/.env.production &&
            echo \"DB_PORT=${{ secrets.DB_PORT }}\" >> /root/hipsta/.env.production &&
            echo \"REDIS_URL=${{ secrets.REDIS_URL }}\" >> /root/hipsta/.env.production &&
            echo \"CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }}\" >> /root/hipsta/.env.production &&
            echo \"CELERY_RESULT_BACKEND=${{ secrets.CELERY_RESULT_BACKEND }}\" >> /root/hipsta/.env.production &&
            echo \"EMAIL_HOST=${{ secrets.EMAIL_HOST }}\" >> /root/hipsta/.env.production &&
            echo \"EMAIL_PORT=${{ secrets.EMAIL_PORT }}\" >> /root/hipsta/.env.production &&
            echo \"EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}\" >> /root/hipsta/.env.production &&
            echo \"EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}\" >> /root/hipsta/.env.production &&
            echo \"EMAIL_USE_TLS=${{ secrets.EMAIL_USE_TLS }}\" >> /root/hipsta/.env.production &&
            echo \"EMAIL_USE_SSL=${{ secrets.EMAIL_USE_SSL }}\" >> /root/hipsta/.env.production &&
            echo \"DEFAULT_FROM_EMAIL=${{ secrets.DEFAULT_FROM_EMAIL }}\" >> /root/hipsta/.env.production &&
            echo \"AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}\" >> /root/hipsta/.env.production &&
            echo \"AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}\" >> /root/hipsta/.env.production &&
            echo \"AWS_STORAGE_BUCKET_NAME=${{ secrets.AWS_STORAGE_BUCKET_NAME }}\" >> /root/hipsta/.env.production &&
            echo \"AWS_REGION=${{ secrets.AWS_REGION }}\" >> /root/hipsta/.env.production &&
            echo \"GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}\" >> /root/hipsta/.env.production &&
            echo \"GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}\" >> /root/hipsta/.env.production &&
            echo \"SOCIAL_PASSWORD=${{ secrets.SOCIAL_PASSWORD }}\" >> /root/hipsta/.env.production &&
            echo \"DEBUG=${{ secrets.DEBUG }}\" >> /root/hipsta/.env.production &&
            echo \"ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}\" >> /root/hipsta/.env.production &&
          
            # Ensure Docker login works on the server
            docker login -u \"${{ secrets.DOCKER_USERNAME }}\" -p \"${{ secrets.DOCKER_PASSWORD }}\" &&
          
            # Pull latest image from Docker Hub
            docker pull jishnu2040/hipsta-backend:latest &&
          
            # Stop any running containers and restart with updated environment variables
            docker-compose -f /root/hipsta/docker-compose.yml --env-file /root/hipsta/.env.production down &&
            docker-compose -f /root/hipsta/docker-compose.yml --env-file /root/hipsta/.env.production up --build -d
          "
