name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with Docker
        run: |
          ssh root@${{ secrets.DO_HOST }} << 'EOF'
          set -e  # Exit on any error

          # Ensure the project directory exists
          if [ ! -d "/root/hipsta" ]; then
            mkdir -p /root/hipsta
            git clone git@github.com:jishnu2040/hipsta.git /root/hipsta
          fi

          cd /root/hipsta

          # Ensure it's a Git repo before pulling
          if [ -d ".git" ]; then
            git reset --hard
            git pull origin main
          fi

          # Pull the latest Docker image
          docker pull jishnu2040/hipsta-backend:latest

          # Create an updated .env file
          cat <<EOT > .env
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          REDIS_URL=${{ secrets.REDIS_URL }}
          EOT

          # Stop old containers, rebuild, and restart services
          docker compose down
          docker compose --env-file .env up --build -d
          EOF
