name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          
          # Check SSH authentication
          ssh -o StrictHostKeyChecking=no -o PubkeyAuthentication=yes -i ~/.ssh/id_rsa root@${{ secrets.DO_HOST }} "echo 'Successfully connected'"

      - name: Deploy with Docker
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DO_HOST }} "
            if [ ! -d '/root/hipsta' ]; then
              git clone git@github.com:jishnu2040/hipsta.git /root/hipsta;
            else
              cd /root/hipsta && git pull origin main;
            fi &&
            docker pull jishnu2040/hipsta-backend:latest &&
            docker-compose -f /root/hipsta/docker-compose.yml --env-file <(echo -e 'SECRET_KEY=${{ secrets.SECRET_KEY }}\nDB_NAME=${{ secrets.DB_NAME }}\nDB_USER=${{ secrets.DB_USER }}\nDB_PASSWORD=${{ secrets.DB_PASSWORD }}\nREDIS_URL=${{ secrets.REDIS_URL }}') up --build -d
          "
